spring:
  application:
    name: store
  datasource:
    url: jdbc:postgresql://localhost:5432/store
    username: storeuser
    password: password
stripe:
  enabled: true
  apiUrl: https://api.stripe.com
  timeout: 1000
  supported-currencies: USD,EUR,GBP
payment-gateway: paypal